import random
import tkinter as tk
from tkinter import Toplevel

# This is the function for generating the strong password.
def passwordGenerator(number_input):
    number_of_characters = number_input
    characters = [random.randint(32,126) for i in range(number_of_characters)] # A random number for accessing the ASCII table is assigned to characters with a range that is the range of the input.
    password = [chr(i) for i in characters] # The password is then generated by accessing the ASCII table for characters
    string = ""
    for i in range(len(password)):
        string = string + password[i] + " "
    return string


number_of_characters = int(input("Enter the number of characters for your password: "))


root = tk.Tk()

root.title("Password Generator")

root.geometry("800x600")

root.resizable(True, True)


def update_text():
    password = passwordGenerator(number_of_characters)
    label1.config(text=password)

button = tk.Button(root, text="Generate Strong Password", command=update_text)
button.pack(pady=10)


password = passwordGenerator(number_of_characters)

label1 = tk.Label(root, text=password)
label1.pack(pady=20)



def get_input():
    user_input = entry.get()
    label2.config(text=f"You entered: {user_input}")
    number_of_characters = user_input
    



root.mainloop()

